CREATE TABLE personas (
	id INT(20) NOT NULL AUTO_INCREMENT,
	apellido VARCHAR(255),
	fecha_nacimiento DATE,
	dni INT(11) NOT NULL,
	nombre VARCHAR(255),
	profesion VARCHAR(255),
	PRIMARY KEY (id) USING BTREE,
	UNIQUE INDEX DNI_UNIQUE (dni) USING BTREE
);


CREATE TABLE USER (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	ENABLED CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID) USING BTREE,
	UNIQUE INDEX NAME_USER_UNIQUE (NOMBRE) USING BTREE
);

ALTER TABLE USER ADD CONSTRAINT ENABLED_USER_CHECK CHECK (ENABLED = 'Y' OR ENABLED = 'N');

INSERT INTO USER (NOMBRE, PASSWORD) VALUES ("ADMIN", "QUU4NDFBVw==");
